const ActionTypes = {
    CHANGE_NAME: 'CHANGE_NAME',
    ADD_TO_LIST: 'ADD_TO_LIST',
    ON_ITEM_COMPLETED: 'ON_ITEM_COMPLETED',
    DELETED_ITEM: 'DELETED_ITEM',
    UPDATED_ITEM: 'UPDATED_ITEM',
    EDIT_MODE: 'EDIT_MODE',
    LOAD_LIST: 'LOAD_LIST'
}

export default ActionTypes;